# Generated by Django 5.0.4 on 2024-04-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('status', models.CharField(default='ไม่ผ่าน', max_length=20)),
                ('inp', models.CharField(max_length=100)),
                ('outp', models.CharField(max_length=100)),
                ('inp_ex', models.CharField(max_length=100)),
                ('outp_ex', models.CharField(max_length=100)),
            ],
        ),
    ]
