# Generated by Django 5.0.4 on 2024-04-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='inp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='outp',
            field=models.CharField(max_length=255),
        ),
    ]
