# Generated by Django 5.0.4 on 2024-04-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_problem_inp_alter_problem_outp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='inp_ex',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='outp_ex',
            field=models.CharField(max_length=255),
        ),
    ]
